### ISSUE TITLE
Get started with simple Hello World 

### ISSUE THREAD

**Issue by carromeu** [mr-phlames/leaf-php-boilerplate#38]
I simply has installed Leaf by Composer and trying to run Hello World code, but:

```
Fatal error: Uncaught Error: Class 'PhpOption\Option' not found in /Users/camilo/Projects/vocabulagro/backend/vendor/illuminate/support/Env.php:100 Stack trace:
#0 /Users/camilo/Projects/vocabulagro/backend/vendor/illuminate/support/helpers.php(265): Illuminate\Support\Env::get('APP_DOWN', NULL)
#1 /Users/camilo/Projects/vocabulagro/backend/vendor/leafs/leaf/src/App.php(1263): env('APP_DOWN')
#2 /Users/camilo/Projects/vocabulagro/backend/index.php(13): Leaf\App->run()
#3 {main} thrown in /Users/camilo/Projects/vocabulagro/backend/vendor/illuminate/support/Env.php on line 100
```

Any help?

**Comment by mychidarko** [comment]
Hi, @carromeu thanks for pointing this out. I'll have this updated, thanks and sorry for the inconvenience.

**Comment by mychidarko** [comment]
You can now update to the latest version, v2.4.1, this will get rid of your problem.🙏
